/**
 * Service Authentication Routes
 * 
 * Routes for managing service-to-service authentication,
 * including token generation, validation, and service registry management.
 */

import { Router, Request, Response } from 'express';
import { serviceAuthService } from '../services/service-auth.service';
import { authenticateToken } from '../middleware/auth.middleware';
import { authenticateService, requireServicePermission } from '../middleware/service-auth.middleware';
import { rateLimitPresets } from '../middleware/rate-limit.middleware';
import logger from '../services/logger.service';

const router = Router();

/**
 * Generate service token (for internal use)
 */
router.post('/token/generate',
  rateLimitPresets.auth,
  authenticateToken, // Require user authentication for token generation
  async (req: Request, res: Response) => {
    try {
      const { serviceId } = req.body;
      const correlationId = (req as any).correlationId;

      if (!serviceId) {
        return res.status(400).json({
          success: false,
          error: 'Service ID is required',
          correlationId,
        });
      }

      // Only allow admin users to generate service tokens
      if (req.user?.role !== 'admin') {
        logger.warn('Unauthorized service token generation attempt', {
          userId: req.user?.id,
          serviceId,
          correlationId,
        });

        return res.status(403).json({
          success: false,
          error: 'Admin access required',
          correlationId,
        });
      }

      const tokenData = serviceAuthService.generateServiceToken(serviceId);

      if (!tokenData) {
        return res.status(400).json({
          success: false,
          error: 'Failed to generate service token',
          correlationId,
        });
      }

      logger.info('Service token generated by admin', {
        adminUserId: req.user.id,
        serviceId,
        correlationId,
      });

      res.json({
        success: true,
        data: tokenData,
        correlationId,
      });

    } catch (error) {
      logger.error('Service token generation failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Token generation failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Refresh service token
 */
router.post('/token/refresh',
  rateLimitPresets.auth,
  async (req: Request, res: Response) => {
    try {
      const { refreshToken } = req.body;
      const correlationId = (req as any).correlationId;

      if (!refreshToken) {
        return res.status(400).json({
          success: false,
          error: 'Refresh token is required',
          correlationId,
        });
      }

      const tokenData = serviceAuthService.refreshServiceToken(refreshToken);

      if (!tokenData) {
        return res.status(401).json({
          success: false,
          error: 'Invalid refresh token',
          correlationId,
        });
      }

      res.json({
        success: true,
        data: tokenData,
        correlationId,
      });

    } catch (error) {
      logger.error('Service token refresh failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Token refresh failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Validate service token
 */
router.post('/token/validate',
  rateLimitPresets.auth,
  async (req: Request, res: Response) => {
    try {
      const { token } = req.body;
      const correlationId = (req as any).correlationId;

      if (!token) {
        return res.status(400).json({
          success: false,
          error: 'Token is required',
          correlationId,
        });
      }

      const payload = serviceAuthService.validateServiceToken(token);

      if (!payload) {
        return res.status(401).json({
          success: false,
          error: 'Invalid token',
          correlationId,
        });
      }

      res.json({
        success: true,
        data: {
          valid: true,
          payload,
        },
        correlationId,
      });

    } catch (error) {
      logger.error('Service token validation failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Token validation failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Revoke service token
 */
router.post('/token/revoke',
  rateLimitPresets.auth,
  authenticateToken,
  async (req: Request, res: Response) => {
    try {
      const { token } = req.body;
      const correlationId = (req as any).correlationId;

      if (!token) {
        return res.status(400).json({
          success: false,
          error: 'Token is required',
          correlationId,
        });
      }

      // Only allow admin users to revoke service tokens
      if (req.user?.role !== 'admin') {
        return res.status(403).json({
          success: false,
          error: 'Admin access required',
          correlationId,
        });
      }

      const revoked = serviceAuthService.revokeServiceToken(token);

      if (!revoked) {
        return res.status(400).json({
          success: false,
          error: 'Failed to revoke token',
          correlationId,
        });
      }

      logger.info('Service token revoked by admin', {
        adminUserId: req.user.id,
        correlationId,
      });

      res.json({
        success: true,
        data: { revoked: true },
        correlationId,
      });

    } catch (error) {
      logger.error('Service token revocation failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Token revocation failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Register new service
 */
router.post('/services/register',
  rateLimitPresets.auth,
  authenticateToken,
  async (req: Request, res: Response) => {
    try {
      const { serviceId, serviceName, permissions } = req.body;
      const correlationId = (req as any).correlationId;

      if (!serviceId || !serviceName || !permissions) {
        return res.status(400).json({
          success: false,
          error: 'Service ID, name, and permissions are required',
          correlationId,
        });
      }

      // Only allow admin users to register services
      if (req.user?.role !== 'admin') {
        return res.status(403).json({
          success: false,
          error: 'Admin access required',
          correlationId,
        });
      }

      const service = serviceAuthService.registerService(
        serviceId,
        serviceName,
        permissions
      );

      logger.info('Service registered by admin', {
        adminUserId: req.user.id,
        serviceId,
        serviceName,
        correlationId,
      });

      res.json({
        success: true,
        data: service,
        correlationId,
      });

    } catch (error) {
      logger.error('Service registration failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Service registration failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * List all services
 */
router.get('/services',
  rateLimitPresets.healthCheck,
  authenticateToken,
  async (req: Request, res: Response) => {
    try {
      const correlationId = (req as any).correlationId;

      // Only allow admin users to list services
      if (req.user?.role !== 'admin') {
        return res.status(403).json({
          success: false,
          error: 'Admin access required',
          correlationId,
        });
      }

      const services = serviceAuthService.listServices();

      res.json({
        success: true,
        data: services,
        correlationId,
      });

    } catch (error) {
      logger.error('Service listing failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Service listing failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Get service statistics
 */
router.get('/services/stats',
  rateLimitPresets.healthCheck,
  authenticateToken,
  async (req: Request, res: Response) => {
    try {
      const correlationId = (req as any).correlationId;

      // Only allow admin users to view service stats
      if (req.user?.role !== 'admin') {
        return res.status(403).json({
          success: false,
          error: 'Admin access required',
          correlationId,
        });
      }

      const stats = serviceAuthService.getServiceStats();

      res.json({
        success: true,
        data: stats,
        correlationId,
      });

    } catch (error) {
      logger.error('Service stats request failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Service stats request failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Deactivate service
 */
router.post('/services/:serviceId/deactivate',
  rateLimitPresets.auth,
  authenticateToken,
  async (req: Request, res: Response) => {
    try {
      const { serviceId } = req.params;
      const correlationId = (req as any).correlationId;

      // Only allow admin users to deactivate services
      if (req.user?.role !== 'admin') {
        return res.status(403).json({
          success: false,
          error: 'Admin access required',
          correlationId,
        });
      }

      const deactivated = serviceAuthService.deactivateService(serviceId);

      if (!deactivated) {
        return res.status(404).json({
          success: false,
          error: 'Service not found',
          correlationId,
        });
      }

      logger.info('Service deactivated by admin', {
        adminUserId: req.user.id,
        serviceId,
        correlationId,
      });

      res.json({
        success: true,
        data: { deactivated: true },
        correlationId,
      });

    } catch (error) {
      logger.error('Service deactivation failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Service deactivation failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Activate service
 */
router.post('/services/:serviceId/activate',
  rateLimitPresets.auth,
  authenticateToken,
  async (req: Request, res: Response) => {
    try {
      const { serviceId } = req.params;
      const correlationId = (req as any).correlationId;

      // Only allow admin users to activate services
      if (req.user?.role !== 'admin') {
        return res.status(403).json({
          success: false,
          error: 'Admin access required',
          correlationId,
        });
      }

      const activated = serviceAuthService.activateService(serviceId);

      if (!activated) {
        return res.status(404).json({
          success: false,
          error: 'Service not found',
          correlationId,
        });
      }

      logger.info('Service activated by admin', {
        adminUserId: req.user.id,
        serviceId,
        correlationId,
      });

      res.json({
        success: true,
        data: { activated: true },
        correlationId,
      });

    } catch (error) {
      logger.error('Service activation failed', {
        error: error instanceof Error ? error.message : 'Unknown error',
        correlationId: (req as any).correlationId,
      });

      res.status(500).json({
        success: false,
        error: 'Service activation failed',
        correlationId: (req as any).correlationId,
      });
    }
  }
);

/**
 * Test endpoint for service authentication
 */
router.get('/test',
  rateLimitPresets.healthCheck,
  authenticateService,
  requireServicePermission('read:test'),
  async (req: Request, res: Response) => {
    const service = (req as any).service;
    const correlationId = (req as any).correlationId;

    res.json({
      success: true,
      data: {
        message: 'Service authentication successful',
        service: {
          serviceId: service.serviceId,
          serviceName: service.serviceName,
          permissions: service.permissions,
        },
        timestamp: new Date().toISOString(),
      },
      correlationId,
    });
  }
);

export default router;